openapi: 3.0.3
info:
  title: Desks - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: /api/v1/
tags:
  - name: desks
    description: Everything about desks
  - name: lists
    description: Lists
paths:
  /desks:
    $ref: './paths.yaml#/Desks'
  /lists:
    $ref: './paths.yaml#/Lists'
  /desks/{id}:
    $ref: './paths.yaml#/Desk'
  /lists/{id}:
    $ref: './paths.yaml#/List'
